name: Label when approved
on: pull_request_review

jobs:
  label-when-approved:
    name: "Label when reviewed"
    runs-on: ubuntu-latest
    steps:
      - name: Get information about the original trigger of the run
        uses: potiuk/get-workflow-origin@v1_6
        id: source-run-info
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}

      - name: Label when reviewing by anyone
        uses: TobKed/label-when-approved-action@v1.4
        id: label-when-approved-by-anyone
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          require_committers_approval: 'true'
          label: 'Reviewed by committer'
          comment: 'PR reviewed by at least one committer and no changes requested.'
          pullRequestNumber: ${{ steps.source-run-info.outputs.pullRequestNumber }}